import { BLOCK_TYPES } from "./blockTypes";

export const BLOCK_LABELS = {
  [BLOCK_TYPES.PUBLICATION_NOTE]: "Publication Note",
  [BLOCK_TYPES.DOCUMENT_NUMBER]: "Document Number",
  [BLOCK_TYPES.DO_NUMBER]: "D.O. Number",
  [BLOCK_TYPES.GOVERNMENT_IDENTITY]: "Government Identity",
  [BLOCK_TYPES.DEPARTMENT_IDENTITY]: "Department Identity",
  [BLOCK_TYPES.PLACE_DATE_LINE]: "Place and Date",
  [BLOCK_TYPES.COMMUNICATION_LABEL]: "Form of Communication",

  [BLOCK_TYPES.TO_BLOCK]: "Addressee",
  [BLOCK_TYPES.SUBJECT_BLOCK]: "Subject",
  [BLOCK_TYPES.SALUTATION_BLOCK]: "Salutation",

  [BLOCK_TYPES.INTRO_PHRASE_BLOCK]: "Body",
  [BLOCK_TYPES.BODY_PARAGRAPH]: "Body",
  [BLOCK_TYPES.NUMBERED_PARAGRAPH]: "Body",
  [BLOCK_TYPES.BULLETED_LIST_BLOCK]: "Body List",
  [BLOCK_TYPES.QUOTED_ORDER_BLOCK]: "Quoted Order",

  [BLOCK_TYPES.SIGNOFF_BLOCK]: "Sign-off",
  [BLOCK_TYPES.SIGNATURE_BLOCK]: "Signatory Name",
  [BLOCK_TYPES.DESIGNATION_CONTACT_BLOCK]: "Signatory Details",

  [BLOCK_TYPES.COPY_TO_BLOCK]: "Copy To",
  [BLOCK_TYPES.ENDORSEMENT_BLOCK]: "Endorsement",
  [BLOCK_TYPES.ENCLOSURE_BLOCK]: "Enclosure",
  [BLOCK_TYPES.PRESS_FORWARDING_BLOCK]: "Press Forwarding",
  [BLOCK_TYPES.GAZETTE_FORWARDING_BLOCK]: "Gazette Forwarding",
  [BLOCK_TYPES.EMBARGO_NOTE]: "Embargo Note",
  [BLOCK_TYPES.ID_NOTE_FOOTER]: "I.D. Note Footer",

  [BLOCK_TYPES.SENDER_NAME_BLOCK]: "Sender Name",
  [BLOCK_TYPES.SENDER_DESIGNATION_BLOCK]: "Sender Designation",
  [BLOCK_TYPES.CONTACT_LINE]: "Contact Line",
  [BLOCK_TYPES.COMPLIMENTARY_CLOSE]: "Complimentary Close",
  [BLOCK_TYPES.RECIPIENT_IDENTITY_BLOCK]: "Recipient Identity",
};
